module.exports = {
    isItMD5: require('./functions/isMD5'),
    isItEquals: require('./functions/isEquals'),
    isItEmpty: require('./functions/isEmpty'),
    isItBool: require('./functions/isBool'),
    isItPalindrome: require('./functions/isPalindrome'),
    isItEndWith: require('./functions/isEndWith'),
    isItASCII: require('./functions/isASCII'),
    isItHexColor: require('./functions/isHexColor'),
    isItMACAddress: require('./functions/isMACAddress'),
    isItAValidEmail: require('./functions/isValidEmail'),
    isItAnIPAddress: require('./functions/isIPAddress'),
    isItAHexaDecimal: require('./functions/isHexaDecimal'),
    isItLowerCased: require('./functions/isLowerCase'),
    isItUpperCased: require('./functions/isUpperCase'),
    isItADataURI: require('./functions/isDataURI'),
    hasAtleastOneUpperCaseLetter: require('./functions/hasAtleastOneUpperCaseLetter'),
    hasAtleastOneLowerCaseLetter: require('./functions/hasAtleastOneLowerCaseLetter'),
    FisherYates: require('./functions/fisher_yates'),
    RgbToHex: require('./functions/rgbToHex'),
    Initials: require('./functions/initials'),
    Camelize: require('./functions/camelize'),
    GUID: require('./functions/guid'),
    CountVowels: require('./functions/vowels')
}