module.exports = {
    Average: require('./functions/average'),
    BaseChange: require('./functions/changeBase'),
    Clamp: require('./functions/clamp'),
    Combination: require('./functions/combination'),
    CountPrimeFactors: require('./functions/countPrimeFactors'),
    Division: require('./functions/division'),
    EuclideanDistance: require('./functions/euclideanDistance'),
    EvenOrOdd: require('./functions/evenOrOdd'),
    Factorial: require('./functions/factorial'),
    Fibonacci: require('./functions/fibonacci'),
    GCD: require('./functions/gcd'),
    HammingDistance: require('./functions/hammingDistance'),
    MaxOrMin: require('./functions/max_min'),
    NthRoot: require('./functions/nthRoot'),
    Permutation: require('./functions/permutation'),
    Pythagoras: require('./functions/pythagoras'),
    Slope: require('./functions/slope'),
    Subtract: require('./functions/subtract'),
    SumOfArray: require('./functions/sum')
};